### ISSUE TITLE
process crash when upload files

### ISSUE THREAD

**Issue by tfzxyinhao** [chenboxiang/fdfs-client#1]
由于我自己封装了一个logger(log4js),还有我使用npm安装is-type-of这个的时候提示不存在
所以我对你的fdfs客户端做了一些修改
1.替换logger为我的logger
2.使用isstream代替is-type-of

最近在上传大概180个的图片的时候,上传到一半数量的图片就会进程崩溃,每次必现
相关代码

<pre>
catch (err) {
   callback(err)
}
</pre>

callback定义

<pre>
callback = function() {
    cleanup();
      if (isFunction(callback)) {
         oriCallback.apply(null, arguments)
    }
};
</pre>

cleanup定义

<pre>
function cleanup() {
   socket.removeListener('data', listener);
   // 关闭连接
   protocol.closeSocket(socket)
}
</pre>

closeSocket定义

<pre>
closeSocket: function(socket) {
   socket.end(protocol.packHeader(protocol.FDFS_PROTO_CMD_QUIT, 0, 0))
}
</pre>

以下是进程崩溃时的调用栈

<pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:130:12)
    at Socket.Writable.write (_stream_writable.js:178:5)
    at Socket.write (net.js:613:40)
    at Socket.Writable.end (_stream_writable.js:333:10)
    at Socket.end (net.js:397:31)
    at Object._.extend.closeSocket (/home/publish/protocol.js:246:16)
    at cleanup (/home/publish/protocol.js:237:22)
    at callback (/home/publish/protocol.js:153:13)
    at Socket.listener (/home/publish/protocol.js:210:25)
    at Socket.EventEmitter.emit (events.js:95:17)
</pre>

**Comment by DesertHunter** [comment]
下载文件失败错误代码：
Error: receive packet errno is: 2
请问如何解决，新手求指教

**Comment by DesertHunter** [comment]
var ws = fs.createWriteStream("e:/app.rar");
        this._fdfs.download(_file_id, ws, function (err) {
            if (err) {
                console.log(err);
                deferred.reject(err.toString());
            }else{

                 deferred.resolve(null);
            }
        });
